### ISSUE TITLE
Should client_num be m?

### ISSUE THREAD

**Issue by crankycoder** [mozilla/CANOSP-2019#17]
pyblack complains that `m` delcared here is unused:

https://github.com/mozilla/CANOSP-2019/blob/f592c21043e087d593ef20e006a0d172eead40b6/simulation_util.py#L101

I think the last argument here `client_num` should be `m` : 

https://github.com/mozilla/CANOSP-2019/blob/f592c21043e087d593ef20e006a0d172eead40b6/simulation_util.py#L103

**Comment by Shivansh2407** [comment]
Have Pulled a Request . Please Review and Check It.
