### ISSUE TITLE
Refactor modules into a PyPI installable package

### ISSUE THREAD

**Issue by crankycoder** [mozilla/CANOSP-2019#21]
The bulk of the code should be put into a pypi package so that we can install this into the server code and have automated test cases.

**Comment by Shivansh2407** [comment]
Can you explain a bit more and please guide as I am a fresher in this open source contribution ....
Thank You

**Comment by dzeber** [comment]
@crankycoder is this issue resolved by merging that PR?

**Comment by crankycoder** [comment]
Ooops - no we're good. There's a PyPI package configuration for this already in `setup.py`
